blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/kleiser135/monolith-template/blob/main/TEMPLATE_GUIDE.md
    about: Check the template guide for setup and customization instructions
  - name: Discussions
    url: https://github.com/kleiser135/monolith-template/discussions
    about: Ask questions and discuss ideas with the community
